POST http://localhost:5000/chat/new

###

POST http://localhost:5000/chat/8a4e139e-2c1d-4e25-9747-1e19773d82e6/send
Content-Type: application/json

{
  "content": "Can I see your dildo collection?"
}

###

GET https://api.adultdatalink.com/redgifs/search?media_type=gif&search_text=dildo&count=2

###

GET http://localhost:5000/chat/20dcfa65-8069-4a38-a099-11ef26fbfbb8/history